{"trial_id": "1", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "input_units", "default": null, "conditions": [], "min_value": 32, "max_value": 256, "step": 32, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "n_layers", "default": null, "conditions": [], "min_value": 1, "max_value": 4, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "conv_0_units", "default": null, "conditions": [], "min_value": 32, "max_value": 256, "step": 32, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "n_connections", "default": null, "conditions": [], "min_value": 1, "max_value": 4, "step": 1, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "n_nodes", "default": 128, "conditions": [], "values": [128, 256, 512, 1024], "ordered": true}}, {"class_name": "Float", "config": {"name": "lr", "default": 0.0001, "conditions": [], "min_value": 0.0001, "max_value": 0.01, "step": null, "sampling": "log"}}, {"class_name": "Int", "config": {"name": "conv_1_units", "default": null, "conditions": [], "min_value": 32, "max_value": 256, "step": 32, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "conv_2_units", "default": null, "conditions": [], "min_value": 32, "max_value": 256, "step": 32, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "conv_3_units", "default": null, "conditions": [], "min_value": 32, "max_value": 256, "step": 32, "sampling": "linear"}}], "values": {"input_units": 160, "n_layers": 2, "conv_0_units": 224, "n_connections": 2, "n_nodes": 1024, "lr": 0.000263474572751995, "conv_1_units": 160, "conv_2_units": 64, "conv_3_units": 32}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/tensorflow/python/eager/execute.py\", line 58, in quick_execute\n    except TypeError as e:\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:\n\nDetected at node 'gradient_tape/categorical_crossentropy/softmax_cross_entropy_with_logits/mul/BroadcastGradientArgs' defined at (most recent call last):\n    File \"<frozen runpy>\", line 198, in _run_module_as_main\n    File \"<frozen runpy>\", line 88, in _run_code\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/ipykernel_launcher.py\", line 18, in <module>\n      app.launch_new_instance()\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n      app.start()\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 739, in start\n      self.io_loop.start()\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/asyncio/base_events.py\", line 604, in run_forever\n      self._run_once()\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/asyncio/base_events.py\", line 1909, in _run_once\n      handle._run()\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/asyncio/events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n      await self.process_one()\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n      await dispatch(*args)\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n      await result\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 359, in execute_request\n      await super().execute_request(stream, ident, parent)\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n      reply_content = await reply_content\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 446, in do_execute\n      res = shell.run_cell(\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n      result = self._run_cell(\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n      result = runner(coro)\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/var/folders/qw/zzk10h6x2xg954j92_5lqnnw0000gn/T/ipykernel_1105/2653933200.py\", line 3, in <module>\n      tuner.search(train_generator,\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 234, in search\n      self._try_run_and_update_trial(trial, *fit_args, **fit_kwargs)\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n      self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n      results = self.run_trial(trial, *fit_args, **fit_kwargs)\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n      obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n      results = self.hypermodel.fit(hp, model, *args, **kwargs)\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n      return model.fit(*args, **kwargs)\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/keras/engine/training.py\", line 1685, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/keras/engine/training.py\", line 1284, in train_function\n      return step_function(self, iterator)\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/keras/engine/training.py\", line 1268, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/keras/engine/training.py\", line 1249, in run_step\n      outputs = model.train_step(data)\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/keras/engine/training.py\", line 1054, in train_step\n      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 585, in minimize\n      grads_and_vars = self._compute_gradients(\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 643, in _compute_gradients\n      grads_and_vars = self._get_gradients(\n    File \"/Users/jaymezhang/opt/anaconda3/envs/ga_dsi_projs/lib/python3.11/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 519, in _get_gradients\n      grads = tape.gradient(loss, var_list, grad_loss)\nNode: 'gradient_tape/categorical_crossentropy/softmax_cross_entropy_with_logits/mul/BroadcastGradientArgs'\nIncompatible shapes: [16,14] vs. [16,10]\n\t [[{{node gradient_tape/categorical_crossentropy/softmax_cross_entropy_with_logits/mul/BroadcastGradientArgs}}]] [Op:__inference_train_function_2954]\n"}